language: python

matrix:
  include:
    - python: 3.7

install:
  # Install dependencies
  - pip install -r requirements.txt

script:
  - make ci_test

after_success:
  - codecov

notifications:
  email: false