language: python

matrix:
  include:
    - python: 3.7

install:
  # Install dependencies
  - pip install -r requirements.txt

script:
  - coverage run run_tests.py
  - flake8 streams

after_success:
  - codecov

notifications:
  email: false